apiVersion: apps/v1
kind: Deployment
metadata:
  name: blade-develop
spec:
  selector:
    matchLabels:
      app: blade-develop
  template:
    metadata:
      labels:
        app: blade-develop
    spec:
      containers:
      - name: blade-develop
        image: 192.168.2.29:8443/springblade/blade-ops/blade-develop:2bd89d87
        args:
          - '--spring.profiles.active=${PROFILE}'
          - '--spring.cloud.nacos.config.server-addr=${NACOS_SERVER_ADDR}'
          - '--spring.cloud.nacos.discovery.server-addr=${NACOS_SERVER_ADDR}'
          - >-
            --spring.cloud.sentinel.transport.dashboard=${SENTINEL_DASHBOARD_ADDR}
          - '--server.port=80'
        imagePullPolicy: Always
        resources: {}
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 80
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 80
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 20
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: blade-config
---

