apiVersion: apps/v1
kind: Deployment
metadata:
  name: blade-ui-admin
spec:
  selector:
    matchLabels:
      app: blade-ui-admin
  template:
    metadata:
      labels:
        app: blade-ui-admin
    spec:
      containers:
      - name: blade-ui-admin
        image: 192.168.2.29:8443/springblade/ui/admin:2bd89d87
        imagePullPolicy: Always
        resources: {}
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 20
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: blade-config
        volumeMounts:
          - name: ui-admin-nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: ui-admin-nginx-config
          configMap:
            name: ui-admin-nginx-config
            items:
            - key: nginx.conf
              path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: ui-admin-headless
  labels:
    app: ui-admin-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 80
      name: ui-admin
      targetPort: 80
  selector:
    app: blade-ui-admin
---
