---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  labels:
    app: redis-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: 192.168.2.29:8443/proxy_cache/library/redis:7.0.0-alpine3.16
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: MASTER
      value: "true"
    - name: nacos.naming.data.warmup
      value: "false"
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: redis-config
        items:
        - key: redis-config
          path: redis.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis-config: ""
---
